config/routes.rb
Rails.application.routes.draw do
  gears_for :gears_users
  namespace :gears do
    resources :users
    resource :user_session, only: [:new, :create, :destroy]
    root 'dashboard#index'
  end
end

app/models/gears.rb
module Gears
  def self.table_name_prefix
    'gears_'
  end
end

app/controllers/gears/dashboard_controller.rb
class Gears::DashboardController < Gears::GearsController
      before_action :authorize!

    def index
    end
end

app/controllers/gears/gears_controller.rb
class Gears::GearsController < ::ApplicationController

  helper_method :user_not_authorized, :current_gears_user, :current_gears_user_session, :authorize!

  def user_not_authorized
    flash[:alert] = "Bu işlemi yapmaya yetkili değilsiniz!"
    redirect_to(gears_root_path)
  end

  def current_gears_user_session
    return @current_gears_user_session if defined?(@current_gears_user_session)
    @current_gears_user_session = Gears::UserSession.find
  end

  def current_gears_user
    return @current_gears_user if defined?(@current_gears_user)
    @current_gears_user = current_gears_user_session && current_gears_user_session.user
  end


  def authorize!
    unless current_gears_user
      session[:return_to] = request.fullpath
      redirect_to new_gears_user_session_path
      return false
    end
  end

end

app/controllers/gears/main_controller.rb
module Gears
  class MainController < GearsController
    layout 'gears/gears'

    require 'gears/gears_helper'
    include Gears::GearsHelper

    before_action :set_record, only: [:show, :edit, :update, :destroy]

    helper_method :attrs_for_index, :attrs_for_form, :resource, :search_fields

    before_action :authorize!
    before_action :authenticate!

    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    helper_method :current_gears_user_session, :current_gears_user, :authorize!


    respond_to :html
    class << self
      # @param [Object] resource
      def resource(resource)
        cattr_accessor :resource
        self.resource = resource
        self.resource.class_eval do
          def self.policy_class
            "Gears::#{self.to_s.demodulize}Policy".constantize
          end
        end
      end

      # @param [Array] params
      def permit(*params)
        cattr_accessor :permitted_params
        self.permitted_params = params
      end

      # @param [Array] attrs
      def attrs_for_index(*attrs)
        cattr_accessor :attrs_for_index
        self.attrs_for_index = attrs
      end

      # @param [Array] attrs
      def attrs_for_form(*attrs)
        cattr_accessor :attrs_for_form
        self.attrs_for_form = attrs
      end

      def search_fields(*attrs)
        cattr_accessor :search_fields
        self.search_fields = attrs
      end

      def policies(&block)
        cattr_accessor :pundit
        policy_class_name = "#{self.resource.to_s.demodulize}Policy"

        Gears.const_set(policy_class_name, Class.new(Gears::ApplicationPolicy))

        # policy_class = <<-PE
        #   class #{policy_class_name} < Gears::ApplicationPolicy
        #   end
        # PE

        # unless Gears.const_defined?("Gears::#{policy_class_name}")
          eval("self.pundit ||= #{policy_class_name}")
          self.pundit.class_eval &block
        # end
      end

    end

    def index
      @search = resource.ransack(params[:q], search_key: :q)
      @search_route = resource.to_s.index(/Gears::/) ? [@search] : [:gears, @search]
      @collection = @search.result.page params[:page]
      @gears_title = t('gears.index_title', resource_name: resource.model_name.human)
      authorize resource
      @search.build_condition
    end

    def show
      authorize @record
      @gears_title = t('gears.show_title', resource_name: resource.model_name.human, resource_id: @record.id)
    end

    def new
      @record = resource.new
      authorize @record
      @gears_title = t('gears.new_title', resource_name: resource.model_name.human)
    end

    def create
      @record = resource.create(record_params)
      authorize @record
      respond_custom(:gears, @record)
    end

    def edit
      policy_scope resource
      authorize @record
      @gears_title = t('gears.edit_title', resource_name: resource.model_name.human, resource_id: @record.id)
    end

    def update
      authorize @record
      @record.update(record_params)
      respond_custom(:gears, @record)
    end

    def destroy
      authorize @record
      @record.destroy
      respond_custom(:gears, @record)
    end

    # protected

    # @return [Object]
    def set_record
      @record = resource.find(params[:id])
    end

    def record_params
      params.require(resource.model_name.singular).permit(self.permitted_params)
    end

    # @return [Object]
    def resource
      self.resource ? self.resource : raise(StandardError, t('gears.resource_raise'))
    end

    # @return [Array]
    def search_fields
      self.search_fields.length < 0 ? self.search_fields : self.attrs_for_index
    end

    # @return [Array]
    def attrs_for_index
      self.attrs_for_index
    end

    # @return [Array]
    def attrs_for_form
      self.attrs_for_form
    end

    def authenticate!
      self.pundit.new(current_gears_user, @record)
    end

    def pundit_user
      current_gears_user
    end

    private
    def respond_custom(*args)
      args[1].to_s.index(/Gears::/) ? respond_with(args[1]) : respond_with(args[0], args[1])
    end
  end
end

app/controllers/gears/user_sessions_controller.rb
class Gears::UserSessionsController < Gears::GearsController
  layout 'layouts/gears/gears_auth'

  def new
    @user = Gears::User.new
  end

  def create
    @user_session = Gears::UserSession.new params.require(:gears_user)
                                        .permit(:login, :password)
    if @user_session.save
      redirect_to gears_root_path
    else
      redirect_to new_gears_user_session_path
    end
  end

  def destroy
    current_gears_user_session.destroy
    redirect_to new_gears_user_session_path
  end
end

app/controllers/gears/users_controller.rb
class Gears::UsersController < Gears::MainController
  resource Gears::User
  permit :email, :login, :name, :role, :password, :password_confirmation


  policies do |policy|
    policy.index do
      user.admin?
    end

    policy.show do
      user.admin?
    end

    policy.newform do
      user.admin?
    end

    policy.create do
      user.admin?
    end

    policy.edit do
      user.admin?
    end

    policy.update do
      user.admin?
    end

    policy.destroy do
      user.admin?
    end
  end
end

app/helpers/gears/gears_helper.rb
module Gears
  module GearsHelper
    def gears_icon(icon)
      "<i class='glyphicon glyphicon-#{icon}'></i>".html_safe
    end

    def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(opts = {})
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade-in") do
                 concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                 concat message
               end)
      end
      nil
    end

    def gears_title(title = nil)
      title ? "#{title} | #{Gears.project_name}" : Gears.project_name
    end

    def link_to_add_search_fields(name, f, type)
      new_object = f.object.send "build_#{type}"
      id = "new_#{type}"
      fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
        render("gears/shared/" + type.to_s + "_fields", f: builder)
      end
      link_to(name, '#', class: "add_search_fields btn btn-info btn-xs", data: {id: id, fields: fields.gsub("\n", "")})
    end
  end
end

app/views/gears/dashboard/index.html.slim
h2 dashboard

app/views/gears/shared/_condition_fields.html.slim
.row
  .col-xs-3
    = f.attribute_fields do |a|
      = a.attribute_select nil, class: 'form-control'
  .col-xs-3
    = f.predicate_select only: %i(cont not_cont eq not_eq gt lt blank null), class: 'form-control'
  .col-xs-5
    = f.value_fields do |v|
      = v.text_field :value, class: 'form-control'
  .col-xs-1
    = link_to fa_icon('remove'), '#', class: 'btn btn-danger btn-xs remove_search_fields'

app/views/gears/shared/_search_bar.html.slim
div.search.well.well-sm
  a.toggle-search-fields.btn.btn-primary.btn-xs href="#"
    = fa_icon('caret-down', text: t('gears.conditions'))

  #search-fields.form-search
    = search_form_for @search_route, class: 'form-search' do |f|

      = f.condition_fields do |c|
        = render 'gears/shared/condition_fields', f: c

      = link_to_add_search_fields fa_icon('plus', text: t('gears.new_condition')), f, :condition

      div.form-group
        = f.submit t('gears.search'), class: 'btn btn-xs btn-primary'

app/views/gears/user_sessions/new.html.slim
= simple_form_for @user, url: gears_user_session_path, method: :post do |f|
  h2 = t('gears.please_signin')
  = f.input :login, required: true, focus: true
  = f.input :password, required: true
  = f.submit t('gears.signin'), class: 'btn btn-primary'

app/views/gears/users/_form.html.slim
= simple_form_for @record, multipart: true do |f|
  = f.error_notification

  = f.input :email
  = f.input :login
  = f.input :name
  = f.input :password
  = f.input :password_confirmation
  = f.input :role, as: :select, collection: Gears::User.roles.keys

  = f.button :submit

app/views/gears/users/edit.html.slim
h2
  = @record.model_name.human
  | &nbsp Düzenle
hr
== render 'form'

= content_for :sidebar do
  li
    = link_to fa_icon('th-list', text: t('gears.back_to_list')), gears_users_path

app/views/gears/users/index.html.slim
h2 = resource.model_name
hr
= render 'gears/shared/search_bar'
table.table.table-striped.table-hovered
  thead
    tr
      th = sort_link(@search, :email)
      th = sort_link(@search, :login)
      th = sort_link(@search, :name)
      th = sort_link(@search, :role)
      th
  tbody
    - @collection.each do |record|
      tr
        td = record.email
        td = record.login
        td = record.name
        td = record.role

        td.text-right
          = link_to fa_icon('edit'), edit_gears_user_path(record), class: 'btn btn-xs btn-primary'
          | &nbsp;
          = link_to fa_icon('trash'), gears_user_path(record), class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: t('gears.delete_confirmation') }


= paginate @collection, views_prefix: 'gears/'

= content_for :sidebar do
  li
    = link_to fa_icon('plus-square', text: t('gears.add_new', resource_name: resource.model_name.human.capitalize)), new_gears_user_path

app/views/gears/users/new.html.slim
h2
  = t('gears.new_record', resource_name: @record.model_name.human)
hr
== render 'form'

= content_for :sidebar do
  li
    = link_to fa_icon('th-list', text: t('gears.back_to_list')), gears_users_path

app/views/gears/users/show.html.slim
h2 = "#{@record.id} Düzenle"
hr

table.table.table-bordered.table-striped
  tbody
    tr
      td = resource.human_attribute_name(:email)
      td = @record.email
    tr
      td = resource.human_attribute_name(:login)
      td = @record.login
    tr
      td = resource.human_attribute_name(:name)
      td = @record.name
    tr
      td = resource.human_attribute_name(:role)
      td = @record.role
= content_for :sidebar do
  li
    = link_to fa_icon('plus-square', text: t('gears.add_new', resource_name: resource.model_name.human.capitalize)), new_gears_user_path
  li
    = link_to fa_icon('edit', text: t('gears.edit')), edit_gears_user_path(@record.id)
  li
    = link_to fa_icon('trash', text: t('gears.delete')), gears_user_path(@record.id), method: :delete, data: {confirm: t('gears.delete_confirmation')}
  li
    = link_to fa_icon('th-list', text: t('gears.back_to_list')), gears_users_path

app/views/layouts/gears/gears.html.slim
doctype html
html
  head
    title
      = gears_title @gears_title
    = stylesheet_link_tag "gears/gears", media: "all"
    = javascript_include_tag "gears/gears"
    = yield :head_inject

    meta name="viewport" content="width=device-width, initial-scale=1"

    = csrf_meta_tags

  body
    .nav.navbar.navbar-default
      .container
        .pull-left
          .navbar-header
            button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
              span class="icon-bar"
              span class="icon-bar"
              span class="icon-bar"
            a.navbar-brand href="#{gears_root_url}" = Gears.project_name
        .pull-right.user-info
          - if current_gears_user_session
            ul
              li = raw t('gears.welcome', name: "#{link_to(current_gears_user.name, gears_user_path(current_gears_user))}")
              - if current_gears_user.admin?
                li = link_to fa_icon('users'), gears_users_path
              li = link_to fa_icon('sign-out'), gears_user_session_path, method: :delete
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav
            li = link_to(fa_icon('dashboard'), gears_root_path)
            = render partial: 'gears/layouts/navigation'

    .container
      = flash_messages
      .row
        .col-sm-8.col-md-8
          == yield
        .col-sm-4.col-md-4
          - if content_for?(:sidebar)
            ul.nav.nav-pills.nav-stacked
              == yield :sidebar

app/views/layouts/gears/gears_auth.html.slim
doctype html
html
  head
    title Oturum Aç
      | Gears CMS
    = stylesheet_link_tag "gears/gears", media: "all"
    = javascript_include_tag "gears/gears"
    = csrf_meta_tags
  body
    .container
      .row
        .col-md-12.col-sm-12
          == yield